# Generated by Django 6.0.4 on 2026-04-26 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dealers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('review', models.TextField()),
                ('purchase', models.BooleanField(default=False)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('car_make', models.CharField(blank=True, max_length=100, null=True)),
                ('car_model', models.CharField(blank=True, max_length=100, null=True)),
                ('car_year', models.IntegerField(blank=True, null=True)),
                ('sentiment', models.CharField(blank=True, max_length=20, null=True)),
                ('dealership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='dealers.dealer')),
            ],
        ),
    ]
